export const CATEGORIES = [
  "Badiiy adabiyot",
  "She'riyat",
  "Tarix",
  "Ilmiy",
  "Bolalar adabiyoti",
  "Dasturlash",
];

export const BOOKS = [
  { title: "O'tkan kunlar", author: "Abdulla Qodiriy", year: 1926, category: "Badiiy adabiyot", price: 65000, amount: 12, hue: 18,
    description: "O'zbek romanchiligining ilk namunasi. Otabek va Kumush muhabbati fonida XIX asr Turkiston hayoti tasvirlanadi." },
  { title: "Mehrobdan chayon", author: "Abdulla Qodiriy", year: 1929, category: "Badiiy adabiyot", price: 58000, amount: 8, hue: 340,
    description: "Qo'qon xonligi saroyidagi fitnalar va Anvar bilan Ra'no sevgisi haqidagi tarixiy roman." },
  { title: "Kecha va kunduz", author: "Abdulhamid Cho'lpon", year: 1936, category: "Badiiy adabiyot", price: 52000, amount: 6, hue: 210,
    description: "Jadidchilik davri ziddiyatlari, Zebi taqdiri orqali millat dardini ifodalagan roman." },
  { title: "Sarob", author: "Abdulla Qahhor", year: 1937, category: "Badiiy adabiyot", price: 48000, amount: 10, hue: 160,
    description: "Saidiyning umid va xatolari — inson ruhiyatini teran ochib bergan psixologik roman." },
  { title: "Yulduzli tunlar", author: "Pirimqul Qodirov", year: 1978, category: "Tarix", price: 72000, amount: 5, hue: 250,
    description: "Zahiriddin Muhammad Bobur hayoti va kurashlari haqidagi mashhur tarixiy roman." },
  { title: "Ulug'bek xazinasi", author: "Odil Yoqubov", year: 1973, category: "Tarix", price: 60000, amount: 7, hue: 200,
    description: "Mirzo Ulug'bekning so'nggi kunlari va uning ilmiy merosi atrofidagi fojia." },
  { title: "Boburnoma", author: "Zahiriddin Muhammad Bobur", year: 1530, category: "Tarix", price: 95000, amount: 4, hue: 30,
    description: "Bobur qalamiga mansub, Markaziy Osiyo va Hindiston tarixiga oid noyob memuar asar." },
  { title: "Shum bola", author: "G'afur G'ulom", year: 1936, category: "Bolalar adabiyoti", price: 35000, amount: 20, hue: 45,
    description: "Sho'x va topqir bolaning sarguzashtlari — o'zbek bolalar adabiyotining sevimli asari." },
  { title: "Sariq devni minib", author: "Xudoyberdi To'xtaboyev", year: 1968, category: "Bolalar adabiyoti", price: 38000, amount: 15, hue: 60,
    description: "Hoshimjonning sehrli qalpoqcha bilan boshidan kechirgan kulgili sarguzashtlari." },
  { title: "Xamsa", author: "Alisher Navoiy", year: 1485, category: "She'riyat", price: 120000, amount: 3, hue: 280,
    description: "Besh dostondan iborat buyuk asar: Hayrat ul-abror, Farhod va Shirin, Layli va Majnun, Sab'ai sayyor, Saddi Iskandariy." },
  { title: "Devoni Foniy", author: "Alisher Navoiy", year: 1490, category: "She'riyat", price: 85000, amount: 0, hue: 300,
    description: "Navoiyning fors tilidagi g'azallar devoni." },
  { title: "Ikki eshik orasi", author: "O'tkir Hoshimov", year: 1986, category: "Badiiy adabiyot", price: 55000, amount: 9, hue: 120,
    description: "Urush yillari va undan keyingi davr odamlari taqdiri haqidagi ko'p ovozli roman." },
  { title: "Dunyoning ishlari", author: "O'tkir Hoshimov", year: 1982, category: "Badiiy adabiyot", price: 42000, amount: 11, hue: 95,
    description: "Ona haqidagi samimiy hikoyalar turkumi." },
  { title: "Tib qonunlari", author: "Abu Ali ibn Sino", year: 1025, category: "Ilmiy", price: 150000, amount: 2, hue: 190,
    description: "O'rta asrlar tibbiyotining ensiklopedik asari — besh kitobdan iborat." },
  { title: "Ziji Ko'ragoniy", author: "Mirzo Ulug'bek", year: 1437, category: "Ilmiy", price: 110000, amount: 3, hue: 230,
    description: "Samarqand rasadxonasida tuzilgan yulduzlar jadvali." },
  { title: "JavaScript: zamonaviy asoslar", author: "Kutubxona jamoasi", year: 2024, category: "Dasturlash", price: 89000, amount: 25, hue: 50,
    description: "ES2024, asinxron dasturlash, modullar va brauzer API'lari haqida amaliy qo'llanma." },
  { title: "Vue 3 bilan ilovalar yaratish", author: "Kutubxona jamoasi", year: 2025, category: "Dasturlash", price: 95000, amount: 18, hue: 150,
    description: "Composition API, Pinia, Vue Router va Vite yordamida zamonaviy frontend." },
  { title: "Node.js va Express 5", author: "Kutubxona jamoasi", year: 2025, category: "Dasturlash", price: 92000, amount: 14, hue: 100,
    description: "REST API, autentifikatsiya, ORM va xavfsizlik — backend dasturlash qo'llanmasi." },
];

export const SENTENCES = [
  "Tong otdi, shahar ko'chalari asta-sekin jonlana boshladi.",
  "U kitobni ochdi va birinchi satrlardanoq o'zini boshqa olamda his qildi.",
  "Har bir sahifa o'quvchiga yangi bir savol va yangi bir javob beradi.",
  "Bilim — eng ishonchli boylik, uni hech kim tortib ola olmaydi.",
  "Kutubxona sukunatida faqat varaqlar shitirlashi eshitilardi.",
  "Ustoz shogirdiga qarab jilmaydi va hikoyasini davom ettirdi.",
  "Yillar o'tdi, ammo bu so'zlar xotiradan o'chmadi.",
  "Insonning qadri uning ishlari bilan o'lchanadi, so'zlari bilan emas.",
  "Daryo bo'yidagi qishloqda hayot o'z maromida davom etardi.",
  "Sabr va mehnat har qanday eshikni ochadi.",
  "U uzoq o'yladi, so'ng qalamni qo'liga olib yozishga tushdi.",
  "Osmonda yulduzlar charaqlar, shamol tol barglarini tebratardi.",
];
